# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: blang/latex

build:
  script:
    xelatex -pdf -xelatex example.tex
  artifacts:
    paths:
      - "*.pdf"
    expire_in: 1 hour
